### ISSUE TITLE
No more Cream and Sugar.

### ISSUE THREAD

**Issue by vaikarai** [bitmakerlabs/nest#17]
Thanks in advance.

**Comment by vaikarai** [comment]
Thanks for the Cream. 

Sugar, Please.

**Comment by lidzeppelin** [comment]
I'll fix that today :)

_Lidia Sienkowska_
Director of Community & Student Experience

Bitmaker Labs
220 King Street West, Suite 200
Toronto ON M5H 1K4

M: (647) 971-3429
E: lidia@bitmakerlabs.com

W: bitmakerlabs.com
T: twitter.com/bitmakerlabs
FB: facebook.com/BitmakerLabs

**Comment by vaikarai** [comment]
Absolutely, No Sugar in the kitchen, now. I would really appreciate, if we have sugar at least for next week.

Thanks in advance.

Senthil

**Comment by lidzeppelin** [comment]
Absolutely. I will get you sugar as soon as I can.

LS

_Lidia Sienkowska_
Director of Community & Student Experience

Bitmaker Labs
220 King Street West, Suite 200
Toronto ON M5H 1K4

M: (647) 971-3429
E: lidia@bitmakerlabs.com

W: bitmakerlabs.com
T: twitter.com/bitmakerlabs
FB: facebook.com/BitmakerLabs

**Comment by vaikarai** [comment]
Thanks for taking care of the Sugar issue, Lidia. One last request from me. We ran out of cream and milk will run out tomorrow. 

Love the big spoon in the sugar container.

Senthil

**Comment by lidzeppelin** [comment]
Absolutely I will come in with more milk and cream. Thank you for bringing it to my attention :)

LS

**Comment by vaikarai** [comment]
Thanks for taking care of this Lidia. I am done complaining.

Senthil
